[metadata]
name = assignment0
version = 1.0
description = A description of your project
long_description = file: README.md
author = Your Name
author_email = r.velagala@ufl.edu
url = https://github.com/vrsmreddy

[options]
packages = find:
exclude =
    tests
    docs
python_requires = >=3.6

[options.extras_require]
testing =
    pytest
    pytest-runner

[aliases]
test = pytest

[tool:pytest]
norecursedirs = .*, CVS, _darcs, {arch}, *.egg, venv

